<?php /* -*- coding: utf-8 -*- */
require_once dirname(dirname(__FILE__)) . '/class/Request.php';
/**
 * Generated by PHPUnit_SkeletonGenerator on 2014-09-19 at 11:40:03.
 */
class RequestTest extends PHPUnit_Framework_TestCase
{
    /**
     * @var Request
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new Request;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers Request::add
     * @todo   Implement testAdd().
     */
    public function testAdd()
    {
        // Remove the following lines when you implement this test.
        $this->object->add("test_add", "テスト・追加");
        $test_add = $this->object->get("test_add");
        $this->assertEquals($test_add, "テスト・追加");
    }

    /**
     * @covers Request::get
     * @todo   Implement testGet().
     */
    public function testGet()
    {
        // Remove the following lines when you implement this test.
        $this->object->add("test_get", "テスト・ゲット");
        $test_get = $this->object->get("test_get");

        $this->assertEquals($test_get, "テスト・ゲット");
    }

    /**
     * @covers Request::translate
     * @todo   Implement testTranslate().
     */
    public function testTranslate()
    {
        // Remove the following lines when you implement this test.
        $test_t = $this->object->add("test_add2", " <p>タグ</p> ");
        $test_t = $this->object->get("test_add2");
        $this->assertEquals($test_t, "タグ");
    }
}
