<?php /* -*- coding: utf-8 -*- */
require_once dirname(dirname(__FILE__)) . '/class/RequestForm.php';
require_once dirname(dirname(__FILE__)) . '/class/RzFormAddress.class.php';
/**
 * Generated by PHPUnit_SkeletonGenerator on 2014-09-19 at 11:40:03.
 */
class RzFormAddressTest extends PHPUnit_Framework_TestCase {
    protected $object;
    private $name;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {

        
        
        
        $form_arr = array('test1' => array('name' => "テストフォーム",
                                           'type' => 'type-address',
                                           'type-address' => 1,
                                           'check-must' => "住所を入力してください"
        ));
        $this->object = new RzFormAddress('test1', $form_arr);
        $request = new RequestForm;
        $this->object->setRequest($request);
        
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
        
        
    }

    /**
     * getForm
     */
    public function testGetForm()
    {

        $output = '都道府県: <select name="test1-1" class="typeSelect test1-1"><option value="">選択してください</option>
<option value="北海道"  >北海道</option>
<option value="青森県"  >青森県</option>
<option value="岩手県"  >岩手県</option>
<option value="宮城県"  >宮城県</option>
<option value="秋田県"  >秋田県</option>
<option value="山形県"  >山形県</option>
<option value="福島県"  >福島県</option>
<option value="茨城県"  >茨城県</option>
<option value="栃木県"  >栃木県</option>
<option value="群馬県"  >群馬県</option>
<option value="埼玉県"  >埼玉県</option>
<option value="千葉県"  >千葉県</option>
<option value="東京都"  >東京都</option>
<option value="神奈川県"  >神奈川県</option>
<option value="新潟県"  >新潟県</option>
<option value="富山県"  >富山県</option>
<option value="石川県"  >石川県</option>
<option value="福井県"  >福井県</option>
<option value="山梨県"  >山梨県</option>
<option value="長野県"  >長野県</option>
<option value="岐阜県"  >岐阜県</option>
<option value="静岡県"  >静岡県</option>
<option value="愛知県"  >愛知県</option>
<option value="三重県"  >三重県</option>
<option value="滋賀県"  >滋賀県</option>
<option value="京都府"  >京都府</option>
<option value="大阪府"  >大阪府</option>
<option value="兵庫県"  >兵庫県</option>
<option value="奈良県"  >奈良県</option>
<option value="和歌山県"  >和歌山県</option>
<option value="鳥取県"  >鳥取県</option>
<option value="島根県"  >島根県</option>
<option value="岡山県"  >岡山県</option>
<option value="広島県"  >広島県</option>
<option value="山口県"  >山口県</option>
<option value="徳島県"  >徳島県</option>
<option value="香川県"  >香川県</option>
<option value="愛媛県"  >愛媛県</option>
<option value="高知県"  >高知県</option>
<option value="福岡県"  >福岡県</option>
<option value="佐賀県"  >佐賀県</option>
<option value="長崎県"  >長崎県</option>
<option value="熊本県"  >熊本県</option>
<option value="大分県"  >大分県</option>
<option value="宮崎県"  >宮崎県</option>
<option value="鹿児島県"  >鹿児島県</option>
<option value="沖縄県"  >沖縄県</option>
</select><br />
市区町村・番地等:<br /><input type="text" name="test1-2"  size="50"  maxlength="100"  value="" /><br />
ビル名・階数等.:<br /> <input type="text" name="test1-3"  size="50"  maxlength="100"  value="" />
';
        

        $result = $this->object->getForm();
        // echo $str;
        $this->assertEquals($result, $output);
    }



    /**
     * check
     */
    public function testCheck() {
        $msg = $this->object->check();
        $this->assertEquals($msg, '<span class="err">住所を入力してください</span>');
    }
    /**
     * @covers Request::translate
     * @todo   Implement testTranslate().
     */
    public function testTranslate()
    {
        // Remove the following lines when you implement this test.

    }
}
